[tool.cibuildwheel]
build = "cp37* cp38* cp39* cp310* cp311*"
skip = "cp36* pp* *-musllinux* *-manylinux_i686 *win32 *win_arm64"
test-requires = "pytest"
test-command = "pytest {package}/tests"
test-skip = "*_arm64 *_universal2:arm64"

[tool.cibuildwheel.linux]
before-build = "pip install auditwheel"
before-test = "yum install -y kde-l10n-Chinese && yum reinstall -y glibc-common"
repair-wheel-command = "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/linux64 && auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
repair-wheel-command = ""