# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Linux

on: [ workflow_dispatch ]

env:
  CTP_VERSION: "6.6.9"

jobs:

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Prepare
        run: |
          pip install -r requirements.txt
      - name: Building Package
        run: |
          cd $CTP_VERSION
          python -m cibuildwheel --platform linux --output-dir ../dist
          ls -al ../dist
#      - name: Publish to test PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository-url: https://test.pypi.org/legacy/
