# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Publish 667

on: [ workflow_dispatch ]

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout openctp-tts-667
        uses: actions/checkout@v3
        with:
          repository: Jedore/openctp-tts-667
          path: openctp-tts-667
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Sync files
        run: python templates/sync.py 667
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Building Package
        working-directory: openctp-tts-667
        run: |
          export CIBW_REPAIR_WHEEL_COMMAND=
          python -m cibuildwheel --platform linux --config-file pyproject.toml --output-dir ../dist
        shell: bash
      - name: Install Package
        run: |
          pip install dist/*.whl
        shell: bash
      - name: Test
        run: |
          pytest tests
      - name: Store Package
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distribution
          path: dist
