# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Mac

on: [ workflow_dispatch ]
env:
  CTP_VERSION: "6.3.15"

jobs:
  build-mac:
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [ "3.7" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare
        run: |
          brew install swig
          pip install -r requirements.txt
      - name: Building Package
        run: |
          cd $CTP_VERSION
          install_name_tool -id @loader_path/libthostmduserapi_se.dylib mac64/libthostmduserapi_se.dylib
          install_name_tool -id @loader_path/libthosttraderapi_se.dylib mac64/libthosttraderapi_se.dylib
          install_name_tool -id @loader_path/libthostmduserapi_se.dylib mac_arm64/libthostmduserapi_se.dylib
          install_name_tool -id @loader_path/libthosttraderapi_se.dylib mac_arm64/libthosttraderapi_se.dylib
          python -m cibuildwheel --platform macos --output-dir ../dist
          ls -al ../dist
      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/


